import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StepProvider } from "./context/stepContext";
import { ShortProvider } from "./context/shortContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ShortProvider>
        <StepProvider>
          <body className={inter.className}>{children}</body>
        </StepProvider>
      </ShortProvider>
    </html>
  );
}
